In [70]:
import numpy as np
import pandas as pd
import copy
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.svm import SVC

In [71]:
dataset = pd.read_csv('./BankChurners.csv')
df = copy.deepcopy(dataset)
df

,Unnamed: 0,Attrition_Flag,Customer_Age,Dependent_count,Education_Level,Income_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,...,Gender_M,Gender_F,Marital_Status_Married,Marital_Status_Single,Marital_Status_Unknown,Marital_Status_Divorced,Card_Category_Blue,Card_Category_Gold,Card_Category_Silver,Card_Category_Platinum
0,0,1.0,0.404255,0.6,0.200000,0.50,0.604651,0.8,0.166667,0.500000,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1,1.0,0.489362,1.0,0.600000,0.00,0.720930,1.0,0.166667,0.333333,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2,2,1.0,0.531915,0.6,0.600000,0.75,0.534884,0.6,0.166667,0.000000,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,3,1.0,0.297872,0.8,0.200000,0.00,0.488372,0.4,0.666667,0.166667,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
4,4,1.0,0.297872,0.6,0.000000,0.50,0.186047,0.8,0.166667,0.000000,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,10122,1.0,0.510638,0.4,0.600000,0.25,0.627907,0.4,0.333333,0.500000,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
10123,10123,0.0,0.319149,0.4,0.493333,0.25,0.279070,0.6,0.333333,0.500000,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10124,10124,0.0,0.382979,0.2,0.200000,0.00,0.534884,0.8,0.500000,0.666667,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
10125,10125,0.0,0.085106,0.4,0.600000,0.25,0.534884,0.6,0.500000,0.500000,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
10126,10126,0.0,0.361702,0.4,0.600000,0.00,0.279070,1.0,0.333333,0.666667,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [72]:
col_1 = df['Attrition_Flag']
col_12 = df.iloc[:,2:29]
x= pd.DataFrame(col_12)  
y= pd.DataFrame(col_1)
print(x)

       Customer_Age  Dependent_count  Education_Level  Income_Category  \
0          0.404255              0.6         0.200000             0.50
1          0.489362              1.0         0.600000             0.00
2          0.531915              0.6         0.600000             0.75
3          0.297872              0.8         0.200000             0.00
4          0.297872              0.6         0.000000             0.50
...             ...              ...              ...              ...
10122      0.510638              0.4         0.600000             0.25
10123      0.319149              0.4         0.493333             0.25
10124      0.382979              0.2         0.200000             0.00
10125      0.085106              0.4         0.600000             0.25
10126      0.361702              0.4         0.600000             0.00

       Months_on_book  Total_Relationship_Count  Months_Inactive_12_mon  \
0            0.604651                       0.8                0.166667
1            0.720930                       1.0                0.166667
2            0.534884                       0.6                0.166667
3            0.488372                       0.4                0.666667
4            0.186047                       0.8                0.166667
...               ...                       ...                     ...
10122        0.627907                       0.4                0.333333
10123        0.279070                       0.6                0.333333
10124        0.534884                       0.8                0.500000
10125        0.534884                       0.6                0.500000
10126        0.279070                       1.0                0.333333

       Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  ...  \
0                   0.500000      0.340190             0.308701  ...
1                   0.333333      0.206112             0.343266  ...
2                   0.000000      0.059850             0.000000  ...
3                   0.166667      0.056676             1.000000  ...
4                   0.000000      0.099091             0.000000  ...
...                      ...           ...                  ...  ...
10122               0.500000      0.077536             0.735399  ...
10123               0.500000      0.085819             0.868494  ...
10124               0.666667      0.120042             0.000000  ...
10125               0.500000      0.116172             0.000000  ...
10126               0.666667      0.270566             0.779102  ...

       Gender_M  Gender_F  Marital_Status_Married  Marital_Status_Single  \
0           0.0       1.0                     0.0                    1.0
1           1.0       0.0                     0.0                    0.0
2           0.0       1.0                     0.0                    1.0
3           1.0       0.0                     0.0                    0.0
4           0.0       1.0                     0.0                    1.0
...         ...       ...                     ...                    ...
10122       0.0       1.0                     0.0                    0.0
10123       0.0       1.0                     1.0                    0.0
10124       1.0       0.0                     0.0                    1.0
10125       0.0       1.0                     0.0                    0.0
10126       1.0       0.0                     0.0                    1.0

       Marital_Status_Unknown  Marital_Status_Divorced  Card_Category_Blue  \
0                         0.0                      0.0                 1.0
1                         1.0                      0.0                 1.0
2                         0.0                      0.0                 1.0
3                         0.0                      1.0                 1.0
4                         0.0                      0.0                 1.0
...                       ...                      ...                 ...
10122                     1.0                      0.0                 1.0
10123                     0.0                      0.0                 1.0
10124                     0.0                      0.0                 1.0
10125                     0.0                      1.0                 1.0
10126                     0.0                      0.0                 0.0

       Card_Category_Gold  Card_Category_Silver  Card_Category_Platinum
0                     0.0                   0.0                     0.0
1                     0.0                   0.0                     0.0
2                     0.0                   0.0                     0.0
3                     0.0                   0.0                     0.0
4                     0.0                   0.0                     0.0
...                   ...                   ...                     ...
10122                 0.0                   0.0                     0.0
10123                 0.0                   0.0                     0.0
10124                 0.0                   0.0                     0.0
10125                 0.0                   0.0                     0.0
10126                 0.0                   0.0                     1.0

[10127 rows x 26 columns]

In [73]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [74]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
kf = KFold(n_splits=10, shuffle=True, random_state=15)
test_errors = []
for train_index, test_index in kf.split(df):
    X_train, X_test = x.values[train_index], x.values[test_index]
    y_train, y_test = y.values[train_index], y.values[test_index]
    clf = SVC(kernel = 'rbf', random_state = 0)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    test_errors.append(precision_score(y_test, y_pred))
print(test_errors)

D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[0.9163916391639164, 0.9346110484780158, 0.9306167400881057, 0.920392584514722, 0.930921052631579, 0.9213483146067416, 0.9042904290429042, 0.921978021978022, 0.9114064230343301, 0.9265033407572383]

In [29]:
test_errors_1=[]
for train_index, test_index in kf.split(df):
    X_train, X_test = x.values[train_index], x.values[test_index]
    y_train, y_test = y.values[train_index], y.values[test_index]
    clf1 = SVC(kernel = 'linear', random_state = 0)
    clf1.fit(X_train, y_train)
    y_pred = clf1.predict(X_test)
    test_errors_1.append(precision_score(y_test, y_pred))
print(test_errors_1)

D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[0.9108910891089109, 0.9201349831271091, 0.9347581552305961, 0.9234135667396062, 0.9299014238773274, 0.918552036199095, 0.9078801331853497, 0.9144736842105263, 0.9102132435465768, 0.927765237020316]

In [30]:
test_errors_2=[]
for train_index, test_index in kf.split(df):
    X_train, X_test = x.values[train_index], x.values[test_index]
    y_train, y_test = y.values[train_index], y.values[test_index]
    clf2 = SVC(kernel = 'poly', random_state = 0)
    clf2.fit(X_train, y_train)
    y_pred = clf2.predict(X_test)
    test_errors_2.append(precision_score(y_test, y_pred))
print(test_errors_2)

D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\python\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[0.9343148357870895, 0.9536500579374276, 0.9455782312925171, 0.941638608305275, 0.950561797752809, 0.9337899543378996, 0.9315849486887116, 0.9400452488687783, 0.9302857142857143, 0.9407744874715261]

In [75]:
print(np.mean(test_errors), np.mean(test_errors_1), np.mean(test_errors_2))

0.9218459594295574 0.9197983552245412 0.9402223884727748

In [76]:
import os
import joblib
dirs = 'testModel'
if not os.path.exists(dirs):
    os.makedirs(dirs)
joblib.dump(clf2, dirs+'/SVM.pkl')

['testModel/SVM.pkl']